services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

